---
name: Build and Release Image
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  release: { types: [ published ] }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/crunchydata-vectorchord
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-versions.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Get dependency versions
        uses: mikefarah/yq@796317b885ae219215caa36e9bdacc87c9962c15 # v4.48.2
        id: get-versions
        with:
          cmd: yq eval -o=json -I=0 versions.yaml

  build-and-push:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      # Prevent a failure in one image from stopping the other builds
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Determine version change
        id: changed-version
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: |
            versions.yaml
            Dockerfile

      - name: Determine image push
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: should-release
        with:
          script: |
            if (context.eventName == "pull_request") return false;
            if (context.eventName == "workflow_dispatch") return true;
            return "${{ steps.changed-version.outputs.any_changed }}" == "true";

      - name: Set major postgres version
        id: version
        run: |
          pg_major=$(echo ${{ matrix.crunchydata }} | cut -d'-' -f2 | cut -d'.' -f1)
          echo "pg_major=$pg_major" >> "$GITHUB_OUTPUT"

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          flavor: |
            latest=false
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.crunchydata }}-${{ matrix.vectorchord }},enable=${{ steps.should-release.outputs.result }}
            type=raw,value=${{ steps.version.outputs.pg_major }}-${{ matrix.vectorchord }},enable=${{ steps.should-release.outputs.result }}
            type=raw,value=${{ matrix.crunchydata }},enable=${{ steps.should-release.outputs.result }}
            type=raw,value=${{ steps.version.outputs.pg_major }},enable=${{ steps.should-release.outputs.result }}

      - name: Build and push image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: ${{ !github.event.pull_request.head.repo.fork && steps.metadata.outputs.tags != '' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CRUNCHYDATA_VERSION=${{ matrix.crunchydata }}
            VECTORCHORD_TAG=${{ matrix.vectorchord }}

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build results
    needs: [build-and-push]
    steps:
      - run: |
          result="${{ needs.build-and-push.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi